CREATE TABLE BCM_SUPPLIER(
    SUPPLIER_ID RAW(16) DEFAULT SYS_GUID(),
    SUPPLIER_NAME VARCHAR2(255),
    SUPPLIER_CONTACT_NAME VARCHAR2(255),
    SUPPLIER_ADDRESS VARCHAR2(255),
    SUPPLIER_FIRST_CONTACT_NUMBER VARCHAR2(8),
    SUPPLIER_SECOND_CONTACT_NUMBER VARCHAR2(8),
    SUPPLIER_EMAIL VARCHAR2(255),
    PRIMARY KEY(SUPPLIER_ID)
);
