CREATE TABLE BCM_INVOICE(
    INVOICE_ID RAW(16) DEFAULT SYS_GUID(),
    INVOICE_REFERENCE VARCHAR2(50),
    INVOICE_DESCRIPTION VARCHAR2(255),
    INVOICE_DATE DATE,
    INVOICE_AMOUNT NUMBER,
    INVOICE_STATUS VARCHAR2(50),
    INVOICE_HOLD_REASON VARCHAR2(255),
    ORDER_ID RAW(16),
    PRIMARY KEY(INVOICE_ID),
    CONSTRAINT FK_INVOICE_ORDER
        FOREIGN KEY (ORDER_ID)
        REFERENCES BCM_ORDER(ORDER_ID)
);
